services:
  - type: web
    name: jdbc-form-app
    env: java
    buildCommand: "echo 'No build command, already built as WAR file'"  # No build command needed if you have already built the WAR file.
    startCommand: "java -jar Jdbc_form_op.war"  # Start the WAR file using the java -jar command.
    plan: free  # Or select another plan (like 'starter' or 'standard')
    port: 8080  # The default port Render binds your app to (usually 8080).
